### ISSUE TITLE
nat_class - dependency on pandas?

### ISSUE THREAD

**Issue by AugustT** [GitTFJ/classecol#2]
`nat_class` is failing due to a dependency on pandas. Since I'm working for R, and I'm not a python user I'm not sure what to do about this. Should this have been handled by the python install or am I expected to install pandas myself? It would be good to cover this in the vignette if the latter, for python newbies like me. Thanks!

**Comment by AugustT** [comment]
I also hit a dependency on tensorflow 2.2 when running 

```r
hun_class(
  text_vector = classecol::clean(df$text, level = "simple"),
  type = "full")
```

from the vignette

```
Error in py_run_file_impl(file, local, convert) : 
  ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\tomaug\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip
```

**Comment by GitTFJ** [comment]
These dependencies should be sorted by the `load_classecol(download_modules = T)` line, but something must have gone wrong. 

Can you run `system("python --version")` to check which python is linked to your path. If using mac, type this `system("python -version")`. This should be python v3.6.x. If not, download python 3.6 with the `addeR:py_download()`

Next, you could always run `classecol::load_classecol(download_models = F, download_modules = T, link_py = F)`, to try and repeat the dependency downloads. 

Finally, the python dependencies can always be installed manually:
**Windows**
```
 shell("python -m pip install --upgrade pip")
 shell("python -m pip install pandas")) 
 shell("python -m pip install tensorflow")) #or for tensorflow
```

**Linux and mac**
```
 system("python3 -m pip3 install --upgrade pip3")
 system("python3 -m pip3 install pandas")) 
 system("python3 -m pip3 install tensorflow")) #or for tensorflow
```

Let me know if this works.

**Comment by AugustT** [comment]
Tsvetoslv also had this problem with pandas. Perhaps the order of install is wrong in the inbuilt function. Running `load_classecol(download_modules = T)` agai seems to solve the problem

**Comment by GitTFJ** [comment]
This is on track to be resolved in the next version release of classecol. In the meantime, running load_classecol(download_modules = T) twice is a temporary solution
