### ISSUE TITLE
nat_class error

### ISSUE THREAD

**Issue by Dr-Nathan-Fox** [GitTFJ/classecol#3]
When running `nat_clas()` I am now presented with the following error:

`2021-11-09 15:27:03.552714: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found

2021-11-09 15:27:03.552929: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

2021-11-09 15:27:24.793260: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers

Error in py_run_file_impl(file, local, convert) : 
  AlreadyExistsError: Another metric with the same name already exists.`

I have tried uninstalling everything and reinstalling it as per the vignette but I still get this error. The error occurs on two separate machines as well.

**Comment by Dr-Nathan-Fox** [comment]
After some reinstalling, this error still appears even when the first two do not.

```
2021-11-09 15:43:31.816937: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers

Error in py_run_file_impl(file, local, convert) : 
  AlreadyExistsError: Another metric with the same name already exists.
```

**Comment by GitTFJ** [comment]
Hi Nathan, it looks to me like some of the python modules (equivalent to R packages) may have been updated, and so it is splitting out errors. I will investigate this week and see if I can get the same error. Two questions:1) What operating system are you using?2) Do you have any other versions of python installed?TOn 9 Nov 2021 20:45, Nathan Fox ***@***.***> wrote:
After some reinstalling, this error still appears even when the first two do not.
2021-11-09 15:43:31.816937: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers

Error in py_run_file_impl(file, local, convert) : 
  AlreadyExistsError: Another metric with the same name already exists.

**Comment by Dr-Nathan-Fox** [comment]
@GitTFJ thanks for getting back to me;

1) I am using windows 10.
2) I uninstalled every instance of python on my machine and followed through the vignette.

I am also getting an error that scikit-learn isn't being installed when I run `load_classecol()`.  Though this seems to be solved by using `shell("python -m pip install scikit-learn")`

**Comment by GitTFJ** [comment]
I suspect it is a simple matter of manually specifying Python module versions. I'll explore this on a windows 10 machine tomorrow

**Comment by GitTFJ** [comment]
@nfox29

I have used a fresh install of Windows 10 and can't manage to replicate your issue. I am happy to have a call with you to see if we can debug it. Contact t.f.johnson(at)sheffield.ac.uk if you want to chat.

I will leave the issue open until a resolution is found

**Comment by GitTFJ** [comment]
I've released the new version of the package. It should be much much much simpler to use now as it's all based in R. This has made it slower, but not by a crazy amount. The package still under going system tests. But it should be relatively robust...
